import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-3 flex justify-between bg-slate-500 text-white">
          <div className="flex gap-2">
            <Link href="/">Home</Link>
            <Link href="/blog">Blog</Link>
            <Link href="/products">Products</Link>
            <Link href="/dashboard">Dashboard</Link>
          </div>
          <div className="flex gap-2">
            <Link href="/login">Login</Link>
            <Link href="/register">Register</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
