import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { Locale } from '@/i18n-config';
import LocaleSwitch from '@/app/components/LocaleSwitch';
import '@/app/globals.css';
import ThemeSwitch from '@/app/components/ThemeSwitch';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SiteLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const { lang = 'uk' } = params;

  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <nav className='p-3 flex justify-between items-center bg-slate-500 text-white'>
            <div className='flex gap-2'>
              <Link href={`/${lang}`}>Home</Link>
              <Link href={`/${lang}/blog`}>Blog</Link>
              <Link href={`/${lang}/products`}>Products</Link>
              <Link href={`/${lang}/dashboard`}>Dashboard</Link>
            </div>
            <div className='flex gap-4'>
              <ThemeSwitch />
              <LocaleSwitch current={lang} />
            </div>
            <div className='flex gap-2'>
              <Link href={`/${lang}/login`}>Login</Link>
              <Link href={`/${lang}/register`}>Register</Link>
            </div>
          </nav>
          <main className='container pt-6 pb-6'>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
