import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Locale } from "@/i18n-config";
import LocaleSwitch from "../../components/page-wrapper/LocaleSwitch";
import "../../globals.css";
import ThemeButton from "@/app/components/page-wrapper/ThemeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const { lang = "uk" } = params;

  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="p-3 flex justify-between bg-slate-500 text-white">
            <div className="flex gap-2">
              <Link href={`/${lang}`}>Home</Link>
              <Link href={`/${lang}/blog`}>Blog</Link>
              <Link href={`/${lang}/products`}>Products</Link>
              <Link href={`/${lang}/dashboard`}>Dashboard</Link>
              {/* <Link href="/landing">Landing</Link> */}
            </div>
            <div>
              <LocaleSwitch current={lang} />
            </div>
            <div>
              <ThemeButton />
            </div>
            <div className="flex gap-2">
              <Link href={`/${lang}/login`}>Login</Link>
              <Link href={`/${lang}/register`}>Register</Link>
            </div>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
